//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public Nullable<byte> is_admin { get; set; }
        public Nullable<int> isyeri_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Isyeri Isyeri { get; set; }
    }
}
