//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int id { get; set; }
        public Nullable<int> stok_adedi { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> depo_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string stok_kodu { get; set; }
    
        public virtual Depo Depo { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
