//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokTakipOtomasyonuEntities1 : DbContext
    {
        public StokTakipOtomasyonuEntities1()
            : base("name=StokTakipOtomasyonuEntities1")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Depo> Depo { get; set; }
        public virtual DbSet<Isyeri> Isyeri { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
    }
}
